---
- hosts: operator
  pre_tasks:
  - name: install epel-release
    yum: name=epel-release
  - name: install pip
    yum: name=python-pip
  - name: pip install docker-py
    pip: name=docker-py version=1.9.0
  roles:
    - docker
    - letsencrypt
    - nginx
