---
- name: install docker
  yum: name=docker
- name: disable selinux in containers
  lineinfile: dest=/etc/sysconfig/docker regexp='(OPTIONS=\'--selinux-enabled --log-driver=journald\')' line="OPTIONS='--selinux-enabled=false --log-driver=journald'"
- name: add overlay storage driver
  lineinfile: dest=/etc/sysconfig/docker-storage regexp='(DOCKER_STORAGE_OPTIONS=)' line="DOCKER_STORAGE_OPTIONS=-s overlay"
- name: enable and start docker
  service:
    enabled: true
    state: started
    name: docker
