---
- name: install certbot
  yum: name=certbot
- name: enable firewalld http service
  command: firewall-cmd --add-service=http
  register: enabled
  changed_when: enabled.stdout == 'success'
- name: enable firewalld https service
  command: firewall-cmd --add-service=https
  register: enabled
  changed_when: enabled.stdout == 'success'
- name: add nginx well-known.conf
  copy: src=files/well-known.conf dest=/etc/nginx/default.d/le-well-known.conf
- name: check letsencrypt cert exists
  stat: path=/etc/letsencrypt/live
  register: cert_exists
- name: create ssl certificate
  command: certbot certonly --webroot --non-interactive --agree-tos --email jared.patrick@gmail.com -d {{inventory_hostname}}.bitwurx.com -d www.{{inventory_hostname}}.bitwurx.com --webroot-path=/usr/share/nginx/html
  when: cert_exists|failed
- name: generate DH group
  shell: if [ ! -f /etc/ssl/certs/dhparam.pem ]; then openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048; else echo "0"; fi
  register: generated
  changed_when: generated.stdout != "0"
- name: add nginx ssl.conf
  template: src=templates/default.j2 dest=/etc/nginx/conf.d/default.conf
- name: add nginx ssl-redirect.conf
  copy: src=files/ssl-redirect.conf dest=/etc/nginx/default.d/ssl-redirect.conf
- name: add letsencrypt renew cron job
  copy: src=files/le_renew_cron dest=/etc/cron.d/le_renew
- name: restart nginx
  service: name=nginx state=restarted
